const colors = {
  light: {
    text: '#1A2033',
    tint: '#1B3A6B',
    background: '#F4F6FA',
    foreground: '#1A2033',
    card: '#FFFFFF',
    cardForeground: '#1A2033',
    primary: '#1B3A6B',
    primaryForeground: '#FFFFFF',
    secondary: '#E8EDF5',
    secondaryForeground: '#1B3A6B',
    muted: '#F0F3F9',
    mutedForeground: '#64748B',
    accent: '#C9A84C',
    accentForeground: '#FFFFFF',
    brand: '#32B432',
    brandDark: '#268C26',
    brandLight: '#E8F7E8',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    success: '#22C55E',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    late: '#F97316',
    lateForeground: '#FFFFFF',
    absent: '#8B5CF6',
    absentForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#E2E8F0',
  },
  radius: 16,
}

export default colors
